# Generated by Django 3.2.7 on 2021-12-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210914_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='estoqueitens',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='EstoqueItens',
        ),
    ]
