# Generated by Django 3.2.7 on 2021-12-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0004_parceiro_suframa'),
        ('prod', '0013_auto_20211223_0837'),
        ('estoque', '0003_auto_20211223_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque_movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('desc', models.CharField(max_length=40)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.prod')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.parceiro')),
            ],
        ),
    ]
