# Generated by Django 3.2.7 on 2022-02-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20220113_1638'),
        ('comercial', '0032_operacao_conta_caixa'),
        ('entradas', '0006_auto_20220119_1643'),
        ('estoque', '0004_estoque_movimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque_movimento',
            old_name='quantidade',
            new_name='qtd_entrada',
        ),
        migrations.AddField(
            model_name='estoque_movimento',
            name='nf_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entradas.nf_entrada'),
        ),
        migrations.AddField(
            model_name='estoque_movimento',
            name='nf_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.entrega'),
        ),
        migrations.AddField(
            model_name='estoque_movimento',
            name='qtd_saida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='estoque_movimento',
            name='qtd_saldo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='estoque_movimento',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.parceiro'),
        ),
    ]
