# Generated by Django 3.2.7 on 2022-02-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0032_operacao_conta_caixa'),
        ('entradas', '0006_auto_20220119_1643'),
        ('estoque', '0005_auto_20220201_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_movimento',
            name='nf_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.nf_entrada_itens'),
        ),
        migrations.AlterField(
            model_name='estoque_movimento',
            name='nf_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.entrega'),
        ),
    ]
