# Generated by Django 3.2.7 on 2022-02-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0014_auto_20220112_1549'),
        ('estoque', '0006_auto_20220201_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('desc', models.CharField(max_length=40)),
                ('qtd_entrada', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('qtd_saida', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('qtd_saldo', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.prod')),
            ],
        ),
    ]
