# Generated by Django 3.2.7 on 2022-02-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_auto_20220203_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque_movimento',
        ),
    ]
