# Generated by Django 3.2.7 on 2021-09-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=15, verbose_name='Código')),
                ('desc', models.CharField(max_length=40, verbose_name='Descrição')),
                ('cod_cyber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=8, verbose_name='NCM')),
                ('desc', models.CharField(max_length=40, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=15, verbose_name='Código')),
                ('desc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('compl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('pLiq', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Peso Líquido')),
                ('pBrt', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Peso Bruto')),
                ('prAq', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Preço Aquisição')),
                ('cmv', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='CMV')),
                ('qEst', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Estoque')),
                ('qEstMin', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Estoque Mínimo')),
                ('qEstMax', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Estoque Máximo')),
                ('qMult', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Qtd. Múltipla de compra')),
                ('qEco', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Qtd. Econômica')),
                ('pzEnt', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Prazo Entrega')),
                ('ipiCompra', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='IPI Compra')),
                ('ipiVenda', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='IPI Compra')),
                ('icmsCompra', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ICMS Compra')),
                ('icmsVenda', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ICMS Venda')),
                ('origFiscal', models.CharField(blank=True, max_length=2, null=True, verbose_name='Origem Fiscal')),
                ('tipoTributacao', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo de Tributação')),
                ('obs', models.TextField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.grupo')),
                ('ncm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.ncm', verbose_name='NCM')),
            ],
        ),
        migrations.CreateModel(
            name='Unid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.CharField(max_length=3, verbose_name='Unidade')),
                ('desc', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ProdComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('codComp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codComp', to='prod.prod', verbose_name='CodComp')),
                ('codProd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codProd', to='prod.prod', verbose_name='CodProd')),
            ],
        ),
        migrations.AddField(
            model_name='prod',
            name='unid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.unid'),
        ),
    ]
