# Generated by Django 3.2.7 on 2021-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20210913_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prod',
            old_name='qEst',
            new_name='qEstoque',
        ),
        migrations.AddField(
            model_name='prod',
            name='NCMCyber',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='grupoCyber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='prCusto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Preço Custo'),
        ),
        migrations.AddField(
            model_name='prod',
            name='prVenda',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Preço Venda'),
        ),
        migrations.AddField(
            model_name='prod',
            name='unidCyber',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
