# Generated by Django 3.2.7 on 2021-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_auto_20210914_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unid',
            name='desc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição'),
        ),
    ]
