# Generated by Django 3.2.7 on 2021-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_alter_unid_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='cod',
            field=models.CharField(max_length=12, verbose_name='NCM'),
        ),
    ]
