# Generated by Django 3.2.7 on 2021-09-16 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prod', '0005_alter_ncm_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=12, verbose_name='Origem Fiscal')),
                ('desc', models.CharField(max_length=40, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=12, verbose_name='Tipo de Produto')),
                ('desc', models.CharField(max_length=40, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='prod',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='criadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prod',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='modificadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prod',
            name='NCMCyber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='origemFiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.origemfiscal'),
        ),
        migrations.AddField(
            model_name='prod',
            name='tipoProduto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.tipoproduto'),
        ),
    ]
