# Generated by Django 3.2.7 on 2021-09-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prod', '0006_auto_20210916_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcomp',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prodcomp',
            name='criadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prodcomp_criou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prodcomp',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prodcomp',
            name='modificadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prodcomp_modificou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prod',
            name='criadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prod_criou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prod',
            name='modificadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prod_modificou', to=settings.AUTH_USER_MODEL),
        ),
    ]
