# Generated by Django 3.2.7 on 2021-09-17 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prod', '0007_auto_20210916_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='criadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_criou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prod',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.grupo'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='modificadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_modificou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prod',
            name='ncm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.ncm', verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='origemFiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.origemfiscal'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='tipoProduto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.tipoproduto'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='unid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.unid'),
        ),
        migrations.AlterField(
            model_name='prodcomp',
            name='codComp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigoComp', to='prod.prod', verbose_name='CodComp'),
        ),
        migrations.AlterField(
            model_name='prodcomp',
            name='codProd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigoProd', to='prod.prod', verbose_name='CodProd'),
        ),
        migrations.AlterField(
            model_name='prodcomp',
            name='criadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodcomp_criou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prodcomp',
            name='modificadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodcomp_modificou', to=settings.AUTH_USER_MODEL),
        ),
    ]
