# Generated by Django 3.2.7 on 2021-10-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0008_auto_20210917_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='fatorUnid',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=15, null=True, verbose_name='Fator de conversão'),
        ),
        migrations.AddField(
            model_name='prod',
            name='unid2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unid2', to='prod.unid'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='unid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unid1', to='prod.unid'),
        ),
    ]
