# Generated by Django 3.2.7 on 2021-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_auto_20211017_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='cod',
            field=models.CharField(max_length=15, unique=True, verbose_name='Código'),
        ),
    ]
