# Generated by Django 3.2.7 on 2021-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0010_alter_prod_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=4, verbose_name='Código')),
                ('desc', models.CharField(max_length=40, verbose_name='Descrição')),
                ('cod_cyber', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='grupo',
            name='cod',
            field=models.CharField(max_length=4, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='cod',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipoproduto',
            name='cod',
            field=models.CharField(max_length=4, verbose_name='Tipo de Produto'),
        ),
    ]
