# Generated by Django 3.2.7 on 2021-12-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0011_auto_20211223_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='subGrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.subgrupo'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.grupo'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='tipoProduto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.tipoproduto'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='unid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unid1', to='prod.unid'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='unid2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unid2', to='prod.unid'),
        ),
    ]
