# Generated by Django 3.2.7 on 2021-12-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20211223_0837'),
        ('prod', '0012_auto_20211223_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='prod',
            name='origFiscal',
            field=models.CharField(blank=True, default='0', max_length=2, null=True, verbose_name='Origem Fiscal'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='origemFiscal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.origemfiscal'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
