# Generated by Django 3.2.7 on 2022-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0014_auto_20220112_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='fase_producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='unidade_produtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=40)),
            ],
        ),
    ]
