# Generated by Django 3.2.7 on 2022-02-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0015_fase_producao_unidade_produtiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('desc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('custo_unit', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('desc', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('desc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('maquina', models.ManyToManyField(to='prod.Maquina')),
                ('tipoServico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.tipo_servico')),
                ('unid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unid_serv', to='prod.unid')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nivel', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('tempo_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('tempo_setup', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('desc_final', models.CharField(max_length=50, verbose_name='Descrição Final')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.prod')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('comp_fis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.prod')),
                ('comp_serv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_serv', to='prod.prod_servico')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prod_serv', to='prod.prod_servico')),
            ],
        ),
    ]
