# Generated by Django 3.2.7 on 2022-04-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0016_maquina_prod_componente_prod_servico_servico_tipo_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prod',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='prodcomp',
            options={'verbose_name': 'Composição', 'verbose_name_plural': 'Composição'},
        ),
        migrations.AddField(
            model_name='prod',
            name='nivel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
