# Generated by Django 3.2.7 on 2022-06-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0017_auto_20220423_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
