# Generated by Django 3.2.7 on 2021-12-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NF_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_num', models.IntegerField(default=0)),
                ('ambiente', models.CharField(blank=True, choices=[('1', 'PRODUCAO'), ('2', 'HOMOLOGACÃO')], default=1, max_length=1, null=True)),
                ('url_notificacao', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_nota_last_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pre_nota_cofins',
            name='pre_nota_impostos',
        ),
        migrations.RemoveField(
            model_name='pre_nota_icms',
            name='pre_nota_impostos',
        ),
        migrations.RemoveField(
            model_name='pre_nota_ipi',
            name='pre_nota_impostos',
        ),
        migrations.RemoveField(
            model_name='pre_nota_pis',
            name='pre_nota_impostos',
        ),
        migrations.AddField(
            model_name='pre_nota_cofins',
            name='pre_nota_produtos',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cofins', to='fiscal.pre_nota_produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_nota_icms',
            name='pre_nota_produtos',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='icms', to='fiscal.pre_nota_produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_nota_ipi',
            name='pre_nota_produtos',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ipi', to='fiscal.pre_nota_produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_nota_pis',
            name='pre_nota_produtos',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pis', to='fiscal.pre_nota_produtos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pre_nota',
            name='ambiente',
            field=models.CharField(blank=True, choices=[('1', 'PRODUCAO'), ('2', 'HOMOLOGACÃO')], default=1, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pre_nota_impostos',
            name='Pre_nota_produtos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impostos', to='fiscal.pre_nota_produtos'),
        ),
        migrations.AlterField(
            model_name='pre_nota_produtos',
            name='pre_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='fiscal.pre_nota'),
        ),
    ]
