# Generated by Django 3.2.7 on 2021-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_auto_20211214_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_nota',
            name='pre_nota_id',
        ),
        migrations.AddField(
            model_name='pre_nota',
            name='num_nf',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
