# Generated by Django 3.2.7 on 2021-12-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_auto_20211217_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFe_transmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nf', models.PositiveIntegerField(default=0)),
                ('nfe_json', models.CharField(blank=True, max_length=3000, null=True)),
                ('nfe_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('nfe_status', models.CharField(blank=True, max_length=40, null=True)),
                ('nfe_motivo', models.CharField(blank=True, max_length=60, null=True)),
                ('nfe_recibo', models.CharField(blank=True, max_length=100, null=True)),
                ('nfe_chave', models.CharField(blank=True, max_length=60, null=True)),
                ('nfe_modelo', models.CharField(blank=True, max_length=4, null=True)),
                ('nfe_log', models.CharField(blank=True, max_length=100, null=True)),
                ('nfe_xml_link', models.CharField(blank=True, max_length=3000, null=True)),
                ('nfe_danfe_link', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nf_config',
            name='access_token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='nf_config',
            name='access_token_secret',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='nf_config',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='nf_config',
            name='consumer_secret',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
