# Generated by Django 3.2.7 on 2021-12-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_auto_20211221_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf_config',
            name='ambiente',
            field=models.CharField(blank=True, choices=[('1', 'PRODUCAO'), ('2', 'HOMOLOGACÃO')], default=2, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='nfe_transmissao',
            name='nfe_json',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='pre_nota_cliente',
            name='pre_nota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='fiscal.pre_nota'),
        ),
    ]
