# Generated by Django 3.2.7 on 2021-12-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_auto_20211221_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_nota',
            name='num_nf',
            field=models.IntegerField(default=0),
        ),
    ]
