# Generated by Django 3.2.7 on 2021-12-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_auto_20211221_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe_transmissao',
            name='pre_nota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retorno', to='fiscal.pre_nota'),
            preserve_default=False,
        ),
    ]
