# Generated by Django 3.2.7 on 2021-12-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0024_alter_entrega_num_nf'),
        ('fiscal', '0011_auto_20211222_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_nota_entrega',
            name='pre_nota',
        ),
        migrations.AddField(
            model_name='pre_nota',
            name='entrega',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='nfe', to='comercial.entrega'),
            preserve_default=False,
        ),
    ]
