# Generated by Django 3.2.7 on 2021-12-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0014_auto_20211222_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfe_transmissao',
            name='erro',
        ),
    ]
