# Generated by Django 3.2.7 on 2022-04-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0017_pre_nota_data_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe_transmissao',
            name='motivo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
