# Generated by Django 3.2.7 on 2021-12-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0025_alter_entrega_status'),
        ('cadastro', '0004_parceiro_suframa'),
        ('prod', '0013_auto_20211223_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='NF_entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('data_emissao', models.DateField()),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_outras_desp', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_total_nota', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='NF_entrada_itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(decimal_places=4, max_digits=13)),
                ('preco_unit', models.DecimalField(decimal_places=4, max_digits=13)),
                ('preco_tot', models.DecimalField(decimal_places=2, max_digits=13)),
                ('aliq_icms', models.DecimalField(decimal_places=1, max_digits=5)),
                ('aliq_ipi', models.DecimalField(decimal_places=1, max_digits=5)),
                ('valor_ipi', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao_entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('data_emissao', models.DateField()),
                ('data_previsao', models.DateField()),
                ('prazo_entrega', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[(0, 'ORÇAMENTO'), (10, 'PEDIDO NOVO'), (20, 'PEDIDO PROGRAMADO'), (30, 'PEDIDO PRONTO PARA FATURAMENTO'), (40, 'PEDIDO FATURADO AGUARDANDO EXPEDIÇÃO'), (50, 'PEDIDO ENTREGUE E ENCERRADO')], max_length=20)),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_outras_desp', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_total_nota', models.DecimalField(decimal_places=2, max_digits=13)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entradas.operacao_entrada')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_compra', to='cadastro.parceiro')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fretes_oc', to='cadastro.parceiro')),
                ('vencimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('data_emissao', models.DateField()),
                ('data_previsao', models.DateField()),
                ('prazo_entrega', models.PositiveSmallIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao_material_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(decimal_places=4, max_digits=13)),
                ('preco_unit', models.DecimalField(decimal_places=4, max_digits=13)),
                ('valor_tot', models.DecimalField(decimal_places=2, max_digits=13)),
                ('aliq_icms', models.DecimalField(decimal_places=1, max_digits=5)),
                ('aliq_ipi', models.DecimalField(decimal_places=1, max_digits=5)),
                ('valor_ipi', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_tot_ipi', models.DecimalField(decimal_places=2, max_digits=13)),
                ('obs', models.CharField(blank=True, max_length=40, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.prod')),
                ('solicitacao_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.solicitacao_material')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_compra_itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(decimal_places=4, max_digits=13)),
                ('preco_unit', models.DecimalField(decimal_places=4, max_digits=13)),
                ('preco_tot', models.DecimalField(decimal_places=2, max_digits=13)),
                ('aliq_icms', models.DecimalField(decimal_places=1, max_digits=5)),
                ('aliq_ipi', models.DecimalField(decimal_places=1, max_digits=5)),
                ('valor_ipi', models.DecimalField(decimal_places=2, max_digits=13)),
                ('obs', models.CharField(blank=True, max_length=40, null=True)),
                ('ordem_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.ordem_compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.prod')),
            ],
        ),
    ]
