# Generated by Django 3.2.7 on 2021-12-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0025_alter_entrega_status'),
        ('cadastro', '0004_parceiro_suframa'),
        ('entradas', '0001_initial'),
        ('prod', '0013_auto_20211223_0837'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao_entrada',
            name='conta_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrada_op_credito', to='financeiro.plano_contas'),
        ),
        migrations.AddField(
            model_name='operacao_entrada',
            name='conta_debito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrada_op_debito', to='financeiro.plano_contas'),
        ),
        migrations.AddField(
            model_name='nf_entrada_itens',
            name='nf_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.nf_entrada'),
        ),
        migrations.AddField(
            model_name='nf_entrada_itens',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.prod'),
        ),
        migrations.AddField(
            model_name='nf_entrada',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entradas.operacao_entrada'),
        ),
        migrations.AddField(
            model_name='nf_entrada',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='cadastro.parceiro'),
        ),
        migrations.AddField(
            model_name='nf_entrada',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fretes_entradas', to='cadastro.parceiro'),
        ),
        migrations.AddField(
            model_name='nf_entrada',
            name='vencimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.vencimento'),
        ),
    ]
