# Generated by Django 3.2.7 on 2022-01-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_auto_20220119_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nf_entrada',
            old_name='base_calc_icms_subst',
            new_name='base_calc_icms_st',
        ),
        migrations.RenameField(
            model_name='nf_entrada',
            old_name='valor_icms_subst',
            new_name='valor_icms_st',
        ),
    ]
