# Generated by Django 3.2.7 on 2022-01-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_auto_20220119_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='nf_entrada_itens',
            name='valor_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='nf_entrada_itens',
            name='valor_total_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
