# Generated by Django 3.2.7 on 2022-02-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_movimento'),
        ('entradas', '0006_auto_20220119_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='nf_entrada_itens',
            name='mov_estoque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_entrada', to='estoque.movimento'),
        ),
    ]
