# Generated by Django 3.2.7 on 2022-02-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0007_nf_entrada_itens_mov_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nf_entrada_itens',
            name='mov_estoque',
        ),
    ]
