# Generated by Django 3.2.7 on 2022-02-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0008_remove_nf_entrada_itens_mov_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf_entrada_itens',
            name='nf_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='entradas.nf_entrada'),
        ),
    ]
