# Generated by Django 3.2.7 on 2022-02-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20220204_1610'),
        ('entradas', '0009_alter_nf_entrada_itens_nf_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf_entrada',
            name='vencimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.vencimento'),
        ),
        migrations.AlterField(
            model_name='ordem_compra',
            name='vencimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.vencimento'),
        ),
    ]
