# Generated by Django 3.2.7 on 2022-02-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20220204_1610'),
        ('entradas', '0010_auto_20220204_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao_entrada',
            name='conta_caixa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entrada_conta_caixa', to='financeiro.plano_contas'),
            preserve_default=False,
        ),
    ]
