# Generated by Django 3.2.7 on 2022-02-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20220113_1638'),
        ('entradas', '0011_operacao_entrada_conta_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf_entrada',
            name='tipo_frete',
            field=models.CharField(blank=True, choices=[('1', 'CIF'), ('2', 'FOB')], default='2', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='nf_entrada',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fretes_entradas', to='cadastro.parceiro'),
        ),
    ]
