# Generated by Django 3.2.7 on 2022-03-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0012_auto_20220209_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_compra',
            name='status',
            field=models.CharField(choices=[('1', 'COTAÇÃO DE PREÇOS'), ('2', 'ORDEM DE COMPRA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordem_compra_itens',
            name='ordem_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='entradas.ordem_compra'),
        ),
    ]
