# Generated by Django 3.2.7 on 2022-03-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0013_auto_20220325_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordem_compra',
            old_name='valor_total_nota',
            new_name='base_calc_icms',
        ),
        migrations.AddField(
            model_name='ordem_compra',
            name='base_calc_icms_st',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='ordem_compra',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='ordem_compra',
            name='valor_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='ordem_compra',
            name='valor_icms_st',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='ordem_compra',
            name='valor_ipi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='ordem_compra',
            name='valor_seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='ordem_compra',
            name='valor_total_oc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
