# Generated by Django 3.2.7 on 2022-04-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20220411_1511'),
        ('entradas', '0015_ordem_compra_itens_valor_icms'),
    ]

    operations = [
        migrations.AddField(
            model_name='nf_entrada',
            name='chave_cyber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nf_entrada',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.plano_contas'),
        ),
        migrations.AddField(
            model_name='nf_entrada_itens',
            name='cfop',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
