# Generated by Django 3.2.7 on 2022-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0017_auto_20220411_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='nf_entrada',
            name='serie_cyber',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='nf_entrada',
            name='serie',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
