# Generated by Django 3.2.7 on 2021-11-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0010_alter_prod_cod'),
        ('cadastro', '0001_initial'),
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('desc_NF', models.CharField(blank=True, max_length=30, null=True, verbose_name='Desc. na NF')),
                ('CFOP', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nome')),
                ('CSOSN', models.CharField(blank=True, choices=[('101', 'TRIBUTADO'), ('102', '...')], max_length=5, null=True, verbose_name='CSOSN')),
                ('Origem_mercadoria', models.CharField(blank=True, choices=[('0', 'NACIONAL'), ('1', 'ESTRANGEIRA')], max_length=5, null=True, verbose_name='CSOSN')),
                ('mensagem_NF', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastro.parceiro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_tranportados', to='cadastro.parceiro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vencimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='comercial.vencimento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='num',
            field=models.CharField(default='0', max_length=15, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_frete',
            field=models.CharField(choices=[('1', 'CIF'), ('2', 'FOB')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido_item',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.prod'),
        ),
        migrations.AlterField(
            model_name='vencimento',
            name='vencimentos',
            field=models.CharField(default='0', max_length=30, verbose_name='Vencimentos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.operacao'),
        ),
    ]
