# Generated by Django 3.2.7 on 2021-11-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_auto_20211127_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_item',
            name='pr_tot',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('0', 'ORÇAMENTO'), ('10', 'PEDIDO NOVO'), ('20', 'PEDIDO PROGRAMADO'), ('30', 'PEDIDO PRONTO PARA FATURAMENTO'), ('40', 'PEDIDO FATURADO AGUARDANDO EXPEDIÇÃO'), ('50', 'PEDIDO ENTREGUE E ENCERRADO')], default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total_entregue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='num',
            field=models.CharField(default='0', max_length=15, unique=True, verbose_name='Número'),
        ),
    ]
