# Generated by Django 3.2.7 on 2021-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_auto_20211130_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_total_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'ORÇAMENTO'), (10, 'PEDIDO NOVO'), (20, 'PEDIDO PROGRAMADO'), (30, 'PEDIDO PRONTO PARA FATURAMENTO'), (40, 'PEDIDO FATURADO AGUARDANDO EXPEDIÇÃO'), (50, 'PEDIDO ENTREGUE E ENCERRADO')], default=0),
        ),
    ]
