# Generated by Django 3.2.7 on 2021-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_auto_20211209_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='Origem_mercadoria',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='desc_NF',
        ),
        migrations.AddField(
            model_name='operacao',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('1', 'NF-e normal'), ('4', 'DevoluçãoA')], max_length=1, null=True, verbose_name='Finalidade'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='natureza_operacao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Desc. na NF'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='origem_mercadoria',
            field=models.CharField(blank=True, choices=[('0', 'NACIONAL'), ('1', 'ESTRANGEIRA')], max_length=1, null=True, verbose_name='CSOSN'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='situacao_tributaria',
            field=models.CharField(choices=[('101', 'Tributada com permissão de crédito'), ('102', 'Tributada sem permissão de crédito'), ('103', 'Isenção do ICMS para faixa de receita bruta'), ('201', 'Tributada com permissão de crédito e com cobrança do ICMS por substituição tributária'), ('202', 'Tributada sem permissão de crédito e com cobrança do ICMS por substituição tributária'), ('203', 'Isenção do ICMS para faixa de receita bruta e com cobrança do ICMS por substituição tributária'), ('300', 'Imune'), ('400', 'Não tributada'), ('500', 'ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação'), ('900', 'Outros')], default=0, max_length=3, verbose_name='Sit. Trib.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacao',
            name='tipo',
            field=models.CharField(choices=[('0', 'ENTRADA'), ('1', 'SAÍDA')], default=1, max_length=1, verbose_name='Movimento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='obs_nf',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido_item',
            name='codigo_cfop',
            field=models.CharField(default=0, max_length=4, verbose_name='CFOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_item',
            name='inf_adic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='obs',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
