# Generated by Django 3.2.7 on 2021-12-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_parceiro_suframa'),
        ('comercial', '0008_auto_20211214_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastro.parceiro'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_transportados', to='cadastro.parceiro'),
        ),
    ]
