# Generated by Django 3.2.7 on 2021-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_auto_20211215_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento_item',
            name='pr_tot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Preço Total.'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='previsao_entrega',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Prazo de entrega'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade_orcamento',
            field=models.PositiveSmallIntegerField(blank=True, default=7, null=True, verbose_name='Validade orcamento'),
        ),
    ]
