# Generated by Django 3.2.7 on 2021-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_auto_20211215_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='num_orc',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Número Orçamento'),
        ),
    ]
