# Generated by Django 3.2.7 on 2021-12-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_alter_orcamento_num_orc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento_item',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.orcamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='num',
            field=models.PositiveIntegerField(default='0', unique=True),
        ),
        migrations.AlterField(
            model_name='pedido_item',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.pedido'),
        ),
    ]
