# Generated by Django 3.2.7 on 2021-12-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_auto_20211216_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_item',
            name='pr_tot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Preço Total.'),
        ),
    ]
