# Generated by Django 3.2.7 on 2021-12-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_pedido_item_pr_tot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='valor_total_pedido',
            new_name='valor_total_entrega',
        ),
        migrations.AddField(
            model_name='comercial_config',
            name='num_ult_entrega',
            field=models.PositiveIntegerField(default='0', verbose_name='Número última entrega'),
        ),
        migrations.AddField(
            model_name='comercial_config',
            name='num_ult_nf',
            field=models.PositiveIntegerField(default='0', verbose_name='Número última NF'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='valor_total_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='entrega_item',
            name='oc_cliente',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='OC Cliente'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Entrega_parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=13, verbose_name='Número')),
                ('vencimento', models.DateTimeField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.entrega')),
            ],
        ),
    ]
