# Generated by Django 3.2.7 on 2021-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_entrega_item_pr_tot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_item',
            name='saldo',
        ),
        migrations.AddField(
            model_name='pedido_item',
            name='qtd_saldo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Saldo Qtd'),
        ),
        migrations.AddField(
            model_name='pedido_item',
            name='valor_saldo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Saldo R$'),
        ),
    ]
