# Generated by Django 3.2.7 on 2021-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_auto_20211217_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega_item',
            name='codigo_cfop',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP'),
        ),
    ]
