# Generated by Django 3.2.7 on 2021-12-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_alter_entrega_item_codigo_cfop'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='classe_imposto',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Classe do imposto'),
        ),
    ]
