# Generated by Django 3.2.7 on 2021-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0022_operacao_classe_imposto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='classe_imposto',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Classe do imposto'),
        ),
    ]
