# Generated by Django 3.2.7 on 2021-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0024_alter_entrega_num_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'RASCUNHO'), (1, 'ERRO NA TRANSMISSÃO'), (2, 'EMITIDA')], default=0),
        ),
    ]
