# Generated by Django 3.2.7 on 2022-01-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0026_alter_orcamento_num_orc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='num_orc',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número Orçamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tipo_frete',
            field=models.CharField(choices=[('1', 'CIF'), ('2', 'FOB')], default='2', max_length=1),
        ),
    ]
