# Generated by Django 3.2.7 on 2022-01-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20220113_1638'),
        ('comercial', '0028_auto_20220117_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastro.parceiro'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_previsao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='num_orc_cli',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número Cliente'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='obs',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='previsao_entrega',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Prazo de entrega'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_frete',
            field=models.CharField(choices=[('1', 'CIF'), ('2', 'FOB')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_transportados', to='cadastro.parceiro'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='validade_orcamento',
            field=models.PositiveSmallIntegerField(blank=True, default=7, null=True, verbose_name='Validade orcamento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_total_orcamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_total_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='vencimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='comercial.vencimento'),
        ),
    ]
