# Generated by Django 3.2.7 on 2022-01-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0029_auto_20220117_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='transportadora',
        ),
    ]
