# Generated by Django 3.2.7 on 2022-01-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20220113_1638'),
        ('comercial', '0030_auto_20220117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastro.parceiro'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.operacao'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.orcamento_origem'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.orcamento_status'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_transportados', to='cadastro.parceiro'),
        ),
    ]
