# Generated by Django 3.2.7 on 2022-02-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0010_auto_20220204_1610'),
        ('financeiro', '0004_auto_20220204_1610'),
        ('comercial', '0032_operacao_conta_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='vencimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='financeiro.vencimento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='vencimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='financeiro.vencimento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vencimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='financeiro.vencimento'),
        ),
        migrations.DeleteModel(
            name='Vencimento',
        ),
    ]
