# Generated by Django 3.2.7 on 2022-03-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0033_auto_20220204_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'RASCUNHO'), (1, 'ERRO NA TRANSMISSÃO'), (2, 'EMITIDA'), (3, 'ENCERRADA')], default=0),
        ),
    ]
