# Generated by Django 3.2.7 on 2021-12-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0025_alter_entrega_status'),
        ('cadastro', '0004_parceiro_suframa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('codigo', models.CharField(blank=True, max_length=4, null=True)),
                ('agencia', models.CharField(blank=True, max_length=6, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('CR', 'CONTAS A RECEBER'), ('CP', 'CONTAS A PAGAR')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Plano_contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CR', 'CONTAS A RECEBER'), ('CP', 'CONTAS A PAGAR')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('CR', 'CONTAS A RECEBER'), ('CP', 'CONTAS A PAGAR')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('desc', models.CharField(max_length=40)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.plano_contas')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.parceiro')),
            ],
        ),
        migrations.CreateModel(
            name='Conta_receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela_num', models.IntegerField(default=0)),
                ('data_emissao', models.DateField()),
                ('vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco')),
                ('conta_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.plano_contas')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.entrega')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.origem')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.status')),
            ],
        ),
        migrations.CreateModel(
            name='Conta_pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela_num', models.IntegerField(default=0)),
                ('data_emissao', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco')),
                ('conta_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.plano_contas')),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.entrega')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.origem')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.status')),
            ],
        ),
    ]
