# Generated by Django 3.2.7 on 2022-02-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0032_operacao_conta_caixa'),
        ('financeiro', '0002_auto_20220124_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_receber',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='comercial.entrega'),
        ),
    ]
