# Generated by Django 3.2.7 on 2022-02-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0009_alter_nf_entrada_itens_nf_entrada'),
        ('financeiro', '0003_alter_conta_receber_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimentos', models.CharField(default='0', max_length=30, verbose_name='Vencimentos')),
            ],
        ),
        migrations.AlterField(
            model_name='conta_pagar',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='entradas.nf_entrada'),
        ),
    ]
