# Generated by Django 3.2.7 on 2022-04-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_parceiro_cod_cyber'),
        ('financeiro', '0006_auto_20220411_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta_pagar',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='cadastro.parceiro'),
        ),
    ]
