# Generated by Django 3.2.7 on 2022-04-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_conta_pagar_parceiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta_pagar',
            old_name='vencimento',
            new_name='data_vencimento',
        ),
        migrations.RenameField(
            model_name='conta_pagar',
            old_name='nf_num',
            new_name='num_nf',
        ),
        migrations.RenameField(
            model_name='conta_pagar',
            old_name='parcela_num',
            new_name='num_parcela',
        ),
    ]
