# Generated by Django 3.2.7 on 2022-06-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta_pagar',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
