# Generated by Django 3.2.7 on 2022-06-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_parceiro_cod_cyber'),
        ('financeiro', '0010_conta_pagar_obs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta_receber',
            options={'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.AddField(
            model_name='conta_receber',
            name='nf_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conta_receber',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conta_receber',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='cadastro.parceiro'),
        ),
    ]
