# Generated by Django 3.2.7 on 2022-06-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_auto_20220617_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta_receber',
            old_name='vencimento',
            new_name='data_vencimento',
        ),
    ]
