# Generated by Django 3.2.7 on 2022-06-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_rename_vencimento_conta_receber_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_receber',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conta_receber',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
