# Generated by Django 3.2.7 on 2021-11-25 17:12

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod', models.IntegerField()),
                ('sigla', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cod', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=35)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_end',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_end', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='2', max_length=2)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome                                      ')),
                ('apelido', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('insc_est', models.CharField(blank=True, max_length=14)),
                ('insc_mun', models.CharField(blank=True, max_length=14)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('fone1', models.CharField(blank=True, max_length=10, null=True)),
                ('fone2', models.CharField(blank=True, max_length=10, null=True)),
                ('email_nfe', models.CharField(blank=True, max_length=60, null=True)),
                ('email_contato', models.CharField(blank=True, max_length=60, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.estado')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.municipio')),
                ('tipo', models.ManyToManyField(to='cadastro.Tipo_parceiro')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_end', models.CharField(max_length=50)),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.estado')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.municipio')),
                ('tipo_end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.tipo_end')),
            ],
        ),
    ]
