# Generated by Django 3.2.7 on 2021-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
