# Generated by Django 3.2.7 on 2021-11-30 12:17

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20211127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='insc_est',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='insc_mun',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='nome',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='tipo',
            field=models.ManyToManyField(blank=True, to='cadastro.Tipo_parceiro'),
        ),
    ]
