# Generated by Django 3.2.7 on 2021-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20211130_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='suframa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
