# Generated by Django 3.2.7 on 2022-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_parceiro_suframa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='apelido',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='insc_est',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='insc_mun',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='nome',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome'),
        ),
    ]
