# Generated by Django 3.2.7 on 2022-01-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20220112_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='insc_est',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='insc_mun',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
