# Generated by Django 3.2.7 on 2022-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20220112_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='obs',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
