# Generated by Django 3.2.7 on 2022-01-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_parceiro_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_parceiro',
            name='sigla',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='pessoa',
            field=models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='J', max_length=2),
        ),
    ]
