# Generated by Django 3.2.7 on 2022-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20220113_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='tipo',
            field=models.ManyToManyField(blank=True, related_name='tipo', to='cadastro.Tipo_parceiro'),
        ),
    ]
