# Generated by Django 3.2.7 on 2022-04-05 21:11

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_parceiro_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razsoc', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome')),
                ('fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('insc_est', models.CharField(blank=True, max_length=31, null=True)),
                ('insc_mun', models.CharField(blank=True, max_length=31, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=60, null=True)),
                ('fone1', models.CharField(blank=True, max_length=15, null=True)),
                ('fone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email_nfe', models.CharField(blank=True, max_length=500, null=True)),
                ('email_contato', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, max_length=5000, null=True)),
                ('suframa', models.CharField(blank=True, max_length=15, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.municipio')),
            ],
        ),
    ]
