# Generated by Django 3.2.7 on 2022-04-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='cod_cyber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
