# Generated by Django 3.2.7 on 2022-07-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=6)),
                ('conta', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, choices=[('RE', 'RECEITA'), ('DE', 'DESPESA'), ('IN', 'INVESTIMENTO')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('desc', models.CharField(max_length=40)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caixa.pessoa')),
            ],
        ),
    ]
