# Generated by Django 3.2.7 on 2022-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_cc_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cc',
            name='bancoo',
            field=models.CharField(blank=True, choices=[('BP', 'BANRISUL PASQUALOTO'), ('BRP', 'BANRISUL RP'), ('SP', 'SICREDI')], max_length=4, null=True),
        ),
    ]
