# Generated by Django 3.2.7 on 2022-07-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_cc_bancoo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cc',
            old_name='bancoo',
            new_name='banco',
        ),
    ]
