# Generated by Django 3.2.7 on 2022-02-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prod', '0015_fase_producao_unidade_produtiva'),
        ('cadastro', '0009_auto_20220113_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='OP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(default=0)),
                ('qtd_programada', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('tempo_estimado', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('momento_ini', models.DateTimeField(blank=True, null=True)),
                ('momento_fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_realizado', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('qtd_realizada', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('qtd_perda', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('setor_produtivo', models.CharField(blank=True, choices=[('1', 'CORTE'), ('2', 'FOB')], max_length=2, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.parceiro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OPs', to='prod.prod')),
            ],
        ),
        migrations.CreateModel(
            name='OP_componente_servico_interno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=0)),
                ('unidade_tempo', models.CharField(choices=[('1', 'MINUTO'), ('60', 'HORAS'), ('480', 'DIAS 8H')], default='1', max_length=6)),
                ('tempo_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('momento_ini', models.DateTimeField(blank=True, null=True)),
                ('momento_fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_realizado', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('tempo_parada', models.IntegerField(default=0)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('custo_total', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_serv_int', to='producao.op')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operador_serv_int', to='cadastro.parceiro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_serv_int', to='prod.prod')),
            ],
        ),
        migrations.CreateModel(
            name='OP_componente_servico_externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_programada', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('qtd_realizada', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('qtd_perda', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('nivel', models.IntegerField(default=0)),
                ('unidade_tempo', models.CharField(choices=[('1', 'MINUTO'), ('60', 'HORAS'), ('480', 'DIAS 8H')], default='1', max_length=6)),
                ('tempo_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('momento_ini', models.DateTimeField(blank=True, null=True)),
                ('momento_fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_realizado', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('tempo_parada', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('custo_total', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_serv_ext', to='producao.op')),
                ('prestador_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operador_serv_ext', to='cadastro.parceiro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_serv_ext', to='prod.prod')),
            ],
        ),
        migrations.CreateModel(
            name='OP_componente_fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_programada', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('qtd_utilizada', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('nivel', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd_perda', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('custo_total', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_comp_fis', to='producao.op')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_fis', to='prod.prod')),
            ],
        ),
    ]
