# Generated by Django 3.2.7 on 2022-02-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20220113_1638'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='op_componente_servico_interno',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operador_serv_int', to='cadastro.parceiro'),
        ),
    ]
