# Generated by Django 3.2.7 on 2022-03-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_alter_op_componente_servico_interno_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'EMITIDA'), ('2', 'PLANEJADA'), ('3', 'PROGRAMADA'), ('4', 'EM PRODUÇÃO'), ('5', 'PRODUÇÃO PARCIAL'), ('6', 'CONCLUÍDA'), ('7', 'ENCERRADA COM SALDO'), ('8', 'CANCELADA')], default='1', max_length=1, null=True),
        ),
    ]
