# Generated by Django 3.2.7 on 2022-07-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_op_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OP_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_reserva', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=13, null=True)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_reserva', to='producao.op')),
            ],
        ),
    ]
